In [1]:
import numpy as np

#NumPy Arrays are faster than Python Lists because of the following reasons:

An array is a collection of homogeneous data-types that are stored in contiguous memory locations. On the other hand, a list in Python is a collection of heterogeneous data types stored in non-contiguous memory locations.
The NumPy package breaks down a task into multiple fragments and then processes all the fragments parallelly.
The NumPy package integrates C, C++, and Fortran codes in Python. These programming languages have very little execution time compared to Python.

#Try this:

a. What is the last element of the output?

print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

b. What is the output of the below code snippet?

arr1=np.array(['Ram','Astha','Brahat'])

arr2=np.array(['Shyam','Kalyan','Naveen'])

arr1>arr2


In [2]:
# part A

print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [3]:
# part B

arr1=np.array(['Ram','Astha','Brahat'])
arr2=np.array(['Shyam','Kalyan','Naveen'])
arr1>arr2

array([False, False, False])

**Problem**:

For below arrays a and b:

a = np.zeros(27).reshape(3, 3, 3)  
b = np.arange(9).reshape(3, 3)  
Which of the following code snippets will give the same output as a+b?

Note: np.newaxis is used to create a new axis in the mentioned dimension.


In [4]:
a = np.zeros(27).reshape(3, 3, 3)
b = np.arange(9).reshape(3, 3)
print(a)
print(b)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
a + b[np.newaxis, :, :]

array([[[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]])

a + b[np.newaxis, :, :] will work here,

b.shape= (3,3) and b[np.newaxis,:,:].shape=(1,3,3) at axis=0 a new dimension is expanded.

a.shape= (3,3,3), at axis=1 and axis=2 b[np.newaxis,:,:] has same dimension, therefore updated b array is broadcasted to axis=0

**Problem**:

Given a Numpy array of integers as input to the function, complete the given function that converts each element in the array into its binary representation.

For example: In binary, 5 = 101, 7= 111, 10= 1010.

Note: You are not allowed to use the inbuilt bin() function and Both input and output array are of datatype 'int'.

Sample Input:  
input = array([[2,3,4],  
               [5,6,7]])  

Sample Output:  
output = array([[01,11,100],  
               [101,110,111]]) 

In [6]:
arr = np.array([[2,3,4],
                [5,6,7]])

def binary(arr):


  binary_repr_v = np.vectorize(np.binary_repr)
  # vectorize func basically helps to iterate the given function(binary_repr) for all the elements in the numpy array.
  return binary_repr_v(arr)

print(binary(arr))

[['10' '11' '100']
 ['101' '110' '111']]
